#!/bin/bash
# BabaChain Configuration Debug Script
# Generated by configure

echo "=== BabaChain Build Configuration Debug ==="
echo "Generated on: $(date)"
echo

echo "=== Host Information ==="
echo "Build system: $build"
echo "Host system: $host"
echo "Target OS: $TARGET_OS"
echo "Cross compiling: $cross_compiling"
echo

echo "=== Compiler Information ==="
echo "CC: $CC"
echo "CXX: $CXX"
echo "CFLAGS: $CFLAGS"
echo "CXXFLAGS: $DEBUG_CXXFLAGS $HARDENED_CXXFLAGS $WARN_CXXFLAGS $NOWARN_CXXFLAGS $ERROR_CXXFLAGS $GPROF_CXXFLAGS $CORE_CXXFLAGS $CXXFLAGS"
echo "CPPFLAGS: $DEBUG_CPPFLAGS $HARDENED_CPPFLAGS $CORE_CPPFLAGS $CPPFLAGS"
echo "LDFLAGS: $PTHREAD_LIBS $HARDENED_LDFLAGS $GPROF_LDFLAGS $CORE_LDFLAGS $LDFLAGS"
echo

echo "=== Build Targets ==="
echo "Build daemon: $build_bitcoind"
echo "Build CLI: $build_bitcoin_cli"
echo "Build TX: $build_bitcoin_tx"
echo "Build wallet tool: $build_bitcoin_wallet"
echo "Build libraries: $build_bitcoin_libs"
echo "Build Qt GUI: $bitcoin_enable_qt"
echo "Build tests: $use_tests"
echo "Build benchmarks: $use_bench"
echo "Build fuzz binary: $enable_fuzz_binary"
echo

echo "=== Features ==="
echo "Wallet support: $enable_wallet"
if test "$enable_wallet" = "yes"; then
  echo "  SQLite support: $use_sqlite"
  echo "  BDB support: $use_bdb"
fi
echo "ZMQ support: $use_zmq"
echo "UPnP support: $use_upnp"
echo "NAT-PMP support: $use_natpmp"
echo "QR code support: $use_qr"
echo "Hardening: $use_hardening"
echo "Debug mode: $enable_debug"
echo

echo "=== Dependencies ==="
echo "libevent: $use_libevent"
if test "$use_libevent" = "yes"; then
  echo "  CFLAGS: $EVENT_CFLAGS"
  echo "  LIBS: $EVENT_LIBS"
fi
echo "GMP: $gmp_found"
if test "$gmp_found" = "yes"; then
  echo "  CFLAGS: $GMP_CFLAGS"
  echo "  LIBS: $GMP_LIBS"
fi
echo

echo "=== PKG-CONFIG Information ==="
echo "PKG_CONFIG: $PKG_CONFIG"
echo "PKG_CONFIG_PATH: $PKG_CONFIG_PATH"
echo "PKG_CONFIG_LIBDIR: $PKG_CONFIG_LIBDIR"
echo

echo "=== Architecture Support ==="
echo "SSSE3: $enable_ssse3"
echo "SSE4.1: $enable_sse41"
echo "SSE4.2: $enable_sse42"
echo "AVX2: $enable_avx2"
echo "x86 AES-NI: $enable_x86_aesni"
echo "x86 SHA-NI: $enable_x86_shani"
echo "ARM AES: $enable_arm_aes"
echo "ARM CRC: $enable_arm_crc"
echo "ARM NEON: $enable_arm_neon"
echo "ARM SHA-NI: $enable_arm_shani"
echo

echo "=== Troubleshooting ==="
echo "If you encounter build issues:"
echo "1. Check that all dependencies are installed"
echo "2. Verify cross-compilation toolchain setup"
echo "3. Check PKG_CONFIG_LIBDIR for cross-compilation"
echo "4. Review compiler and linker flags for conflicts"
echo "5. Try with --disable-hardening if hardening flags cause issues"
echo
