# syntax=docker/dockerfile:1.3

FROM --platform=$BUILDPLATFORM ubuntu:jammy as builder
RUN apt-get update && \
    apt-get -y install --no-install-recommends \
    automake \
    autotools-dev \
    bsdmainutils \
    build-essential \
    ca-certificates \
    curl \
    g++-arm-linux-gnueabihf \
    libtool \
    pkg-config \
    python3 \
    wget \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /home/babachain

COPY . .

ARG TARGETPLATFORM

RUN case "$TARGETPLATFORM" in \
  "linux/arm64") make HOST=arm-linux-gnueabihf -C depends -j`nproc | awk '{x=$1/2; print x}'` ;; \
  "linux/amd64") make HOST=x86_64-pc-linux-gnu -C depends -j`nproc | awk '{x=$1/2; print x}'` ;; \
  *) exit 1 ;; \
esac

RUN ./autogen.sh && \
  case "$TARGETPLATFORM" in \
  "linux/arm64") ./configure --prefix=`pwd`/depends/arm-linux-gnueabihf ;; \
  "linux/amd64") ./configure --prefix=`pwd`/depends/x86_64-pc-linux-gnu ;; \
esac

RUN make -j`nproc | awk '{x=$1/2; print x}'` && make install

RUN mkdir built-target && \
  case "$TARGETPLATFORM" in \
  "linux/arm64") cp depends/arm-linux-gnueabihf/bin/babachain* /home/babachain/built-target ;; \
  "linux/amd64") cp depends/x86_64-pc-linux-gnu/bin/babachain* /home/babachain/built-target ;; \
esac

FROM ubuntu:jammy
LABEL maintainer="BabaChain Developers <dev@babachain.org>"
LABEL description="Dockerised BabaChainCore"

ARG USER_ID
ARG GROUP_ID
ARG TAG

ENV HOME="/home/babachain"

# add user with specified (or default) user/group ids
ENV USER_ID="${USER_ID:-1000}"
ENV GROUP_ID="${GROUP_ID:-1000}"
RUN groupadd -g ${GROUP_ID} babachain && \
    useradd -u ${USER_ID} -g babachain -s /bin/bash -m -d /home/babachain babachain  && \
    mkdir /home/babachain/.babachaincore && \
    chown ${USER_ID}:${GROUP_ID} -R /home/babachain

RUN apt-get update && \
    apt-get -y install --no-install-recommends \
    wget \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /home/babachain/built-target/babachain* /usr/local/bin

USER babachain

VOLUME ["/home/babachain"]

COPY docker/docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 9998 9999 19998 19999

WORKDIR /home/babachain
