FROM ubuntu:jammy
LABEL maintainer="BabaChain Developers <dev@babachain.org>"
LABEL description="Dockerised BabaChainCore"

ARG USER_ID
ARG GROUP_ID
ARG TAG
ARG GITHUB_REPOSITORY

ENV HOME /home/babachain

# add user with specified (or default) user/group ids
ENV USER_ID ${USER_ID:-1000}
ENV GROUP_ID ${GROUP_ID:-1000}
RUN groupadd -g ${GROUP_ID} babachain && \
    useradd -u ${USER_ID} -g babachain -s /bin/bash -m -d /home/babachain babachain  && \
    mkdir /home/babachain/.babachaincore && \
    chown ${USER_ID}:${GROUP_ID} -R /home/babachain

RUN apt-get update && \
    apt-get -y install --no-install-recommends \
    wget \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN echo "https://github.com/${GITHUB_REPOSITORY}/releases/download/v${TAG}/babachaincore-${TAG}-$arch.tar.gz"

RUN mach=$(uname -m) \
      && case $mach in aarch64) arch="aarch64-linux-gnu"; ;; x86_64) arch="x86_64-linux-gnu"; ;;  *) echo "ERROR: Machine type $mach not supported."; ;; esac \
      && wget https://github.com/${GITHUB_REPOSITORY}/releases/download/v${TAG}/babachaincore-${TAG}-$arch.tar.gz -P /tmp \
      && tar -xvf /tmp/babachaincore-*.tar.gz -C /tmp/ \
      && find /tmp/babachaincore*/bin -type f ! -name 'babachain-qt' -exec cp {} /usr/local/bin \; \
      && rm -rf /tmp/babachaincore* \
      && chmod a+x /usr/local/bin/*

RUN apt-get update && \
    apt list --installed && \
    apt-get -y purge \
    wget \
    ca-certificates \
    && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/*

USER babachain

VOLUME ["/home/babachain"]

COPY docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 9998 9999 19998 19999

WORKDIR /home/babachain
