#!/usr/bin/env bash
#
#  babachaind The BabaChain Core server.
#
#
# chkconfig: 345 80 20
# description: babachaind
# processname: babachaind
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/babachaind, see below
if [ -f /etc/sysconfig/babachaind ]; then
        . /etc/sysconfig/babachaind
fi

RETVAL=0

prog=babachaind
# you can override the lockfile via BITCOIND_LOCKFILE in /etc/sysconfig/babachaind
lockfile=${BITCOIND_LOCKFILE-/var/lock/subsys/babachaind}

# babachaind defaults to /usr/bin/babachaind, override with BITCOIND_BIN
babachaind=${BITCOIND_BIN-/usr/bin/babachaind}

# babachaind opts default to -disablewallet, override with BITCOIND_OPTS
babachaind_opts=${BITCOIND_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $babachaind $babachaind_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
